const descriptions = ["Data is not loading.",
"My Internet is too slow.",
"I can't connect to the network.",
"Call drops frequently.",
"Why is the network coverage so poor?",
"Network fluctuates during calls.",
"Unable to send or receive SMS.",
"My data keeps disconnecting.",
"I can't browse websites.",
"Unable to access 5G services.",
"Phone signal keeps going in and out.",
"Mobile hotspot isn't working.",
"VoLTE isn't enabled on my phone.",
"Can't activate my new SIM card.",
"Slow upload speeds.",
"My mobile data is unresponsive.",
"Internet connection keeps failing.",
"Why is my roaming not working?",
"Poor call quality.",
"I can't recharge my account online.",
"Can't check my balance.",
"Data keeps running out quickly.",
"Can't connect to Wi-Fi.",
"I’ve been charged for unused data.",
"Incoming calls are blocked.",
"No network signal in my area.",
"My SIM card got deactivated.",
"Why is 4G slower than expected?",
"Can't activate my data plan.",
"Data speed drops drastically at night.",
"Phone constantly searching for signal.",
"Text messages aren't being delivered.",
"Unable to make international calls.",
"Frequent disconnections during video calls.",
"Getting network errors when browsing.",
"Why is the Internet not stable?",
"My bill is higher than expected.",
"Can't send MMS messages.",
"I keep losing 4G connectivity.",
"Why does my phone show no service?",
"Calls are breaking up too often.",
"Mobile data not working outside the city.",
"Data limits are not accurate.",
"Can't change my data plan online.",
"Why is the network so weak in crowded areas?",
"Getting random call drops.",
"Wi-Fi calling not working on my device.",
"Poor download speed on my mobile.",
"Why am I getting a network busy signal?",
"Frequent buffering while streaming.",
"Data cap reached too quickly.",
"Why does my data stop working at specific times?",
"Phone stuck on emergency calls only.",
"Network congestion during peak hours.",
"My recharge was unsuccessful.",
"Mobile data icon shows no connection.",
"My calls are not connecting overseas.",
"Experiencing slow network indoors.",
"Internet disconnects when moving locations.",
"My phone won't switch from 3G to 4G.",
"SIM not registering on the network.",
"Can't connect to public Wi-Fi.",
"Why is my plan not activating?",
"Getting static on phone calls.",
"Mobile signal drops when indoors.",
"I can't send messages on certain apps.",
"Data network keeps freezing.",
"Can't make calls despite full signal.",
"My phone doesn't detect any network.",
"Unable to download apps on mobile data.",
"Inconsistent data speeds throughout the day.",
"My video calls are lagging.",
"Why can't I send international SMS?",
"Poor network coverage in rural areas.",
"SIM card registration failed.",
"Data charges are too high.",
"Calls drop every few minutes.",
"My Internet stops working while on calls.",
"SIM not recognized after update.",
"Can't activate VoWiFi on my phone.",
"Why do my calls sound garbled?",,
"Mobile data drains battery too fast.",
"Can't access customer support via phone.",
"Why do I get no service in specific locations?",
"Internet lags during peak hours.",
"Frequent connection timeouts.",
"Unable to register on the network.",
"Network speeds drastically reduced after limit.",
"Why can't I receive certain calls?",
"Why is there no LTE signal in my area?",
"Wi-Fi signal is dropping randomly.",
"My phone can't switch between networks.",
"Network settings keep resetting.",
"Unable to tether data from my phone.",
"Mobile data keeps fluctuating.",
"I can't verify my identity with mobile.",
"Unable to make VoIP calls.",
"My incoming calls are being blocked.",
"Can't switch between networks automatically.",
"Network keeps reconnecting during calls."
]

async function getRandomDescription() {
    return descriptions[Math.floor(Math.random() * descriptions.length)];
}

module.exports = getRandomDescription;